part4-ML/from_1021_Django/django_movie/movie_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

part4-ML/from_1021_Django/django_movie/movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/edit/', views.edit, name="edit"),
    path('<int:pk>/update/', views.update, name="update"),
    path('<int:pk>/delete/', views.delete, name="delete"),
]

part4-ML/from_1021_Django/django_movie/movies/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Movies(models.Model):
    title = models.CharField(max_length=50)
    title_en = models.CharField(max_length=50)
    audience = models.IntegerField()
    open_date = models.DateTimeField()
    genre = models.CharField(max_length=20)
    watch_grade = models.CharField(max_length=20)
    score = models.FloatField()
    poster_url = models.CharField(max_length=500)
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        pass
    

part4-ML/from_1021_Django/django_movie/movies/views.py
from django.shortcuts import render, redirect
from .models import Movies

# Create your views here.
def index(request):
    movies = Movies.objects.all()
    context = {
        'movies' : movies,
    }
    return render(request, 'movies/index.html', context)

def new(request):
    return render(request, 'movies/new.html')

def create(request):
    movie = Movies()
    movie.title = request.POST.get("title")
    movie.title_en = request.POST.get("title_en")
    movie.audience = request.POST.get("audience")
    movie.open_date = request.POST.get("open_date")
    movie.genre = request.POST.get("genre")
    movie.watch_grade = request.POST.get("watch_grade")
    movie.score = request.POST.get("score")
    movie.poster_url = request.POST.get("poster_url")
    movie.description = request.POST.get("description")
    movie.save()
    return redirect('movies:detail', movie.pk)

def detail(request, pk):
    movie = Movies.objects.get(pk=pk)
    # print(type(movie.open_date))
    context = {
        'movie' : movie
    }
    return render(request, 'movies/detail.html', context)
    
def edit(request, pk):
    movie = Movies.objects.get(pk=pk)
    if request.method == "POST":
        context = {
            'movie' : movie
        }
        return render(request, 'movies/edit.html', context)
    else:
        return redirect('movies:detail', movie.pk)

def update(request, pk):
    movie = Movies.objects.get(pk=pk)
    if request.method == "POST":
        movie.title = request.POST.get("title")
        movie.title_en = request.POST.get("title_en")
        movie.audience = request.POST.get("audience")
        movie.open_date = request.POST.get("open_date")
        movie.genre = request.POST.get("genre")
        movie.watch_grade = request.POST.get("watch_grade")
        movie.score = request.POST.get("score")
        movie.poster_url = request.POST.get("poster_url")
        movie.description = request.POST.get("description")
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        return redirect('movies:detail', movie.pk)

def delete(request, pk):
    if request.method == "POST":
        movie = Movies.objects.get(pk=pk)
        movie.delete()
    else:
        pass
    return redirect('movies:index')

part4-ML/from_1021_Django/django_movie/movie_crud/templates/base.html
<!-- movie_crud/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <a href="{% url 'movies:index' %}">[HOME]</a>
        {% block content %}
        {% endblock %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

part4-ML/from_1021_Django/django_movie/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ movie.title }}</h2>
<h3>{{ movie.title_en }}</h3>
<p>관객 수 : {{ movie.audience }}</p>
<p>개봉일 : {{ movie.open_date }}</p>
<p>장르 : {{ movie.genre }}</p>
<p>시청등급 : {{ movie.watch_grade }}</p>
<p><a href="{{ movie.poster_url }}">URL</a></p>
<img src="{{ movie.poster_url }}" alt="이미지" width="350" height="500">
<p>상세 설명 : {{ movie.description }}</p>
<hr>
<a href="{% url 'movies:index' %}">[목록으로]</a>
<form action="{% url 'movies:edit' movie.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="수정하기">
</form>
<form action="{% url 'movies:delete' movie.pk %}" method="POST" onclick="return confirm('정말 삭제하시겠습니까?')">
    {% csrf_token %}
    <input type="submit" value="삭제하기">
</form>
{% endblock %}

part4-ML/from_1021_Django/django_movie/movies/templates/movies/edit.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:update' movie.pk %}" method="POST">
{% csrf_token %}
<input type="text" name="title" value="{{ movie.title }}"> 
<input type="text" name="title_en" value="{{ movie.title_en }}">
<input type="number" name="audience" value="{{ movie.audience }}">
<input type="date" name="open_date" value="{{ movie.open_date|date:'Y-m-d' }}">
<input type="text" name="genre" value="{{ movie.genre }}">
<input type="text" name="watch_grade" value="{{ movie.watch_grade }}">
<input type="number" name="score" value="{{ movie.score }}">
<input type="text" name="poster_url" value="{{ movie.poster_url }}">
<textarea name="description" id="" cols="30" rows="10" >{{ movie.description }}</textarea>
<input type="submit" value="submit">
</form>
{% endblock %}

part4-ML/from_1021_Django/django_movie/movies/templates/movies/index.html
{% extends 'base.html' %}
<h1 class='text-center'>MOVIES</h1>
{% block content %}
<h2><a href="{% url 'movies:new' %}">새 영화 정보 생성</a></h2>
{% for movie in movies %}
<hr>
<p>제목 : <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></p>
<p>장르 : {{ movie.genre }}</p>
<p>평점 : {{ movie.score }}</p>
{% endfor %}
{% endblock %}

part4-ML/from_1021_Django/django_movie/movies/templates/movies/new.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:create' %}" method="POST">
{% csrf_token %}
<input type="text" name="title">
<input type="text" name="title_en">
<input type="number" name="audience">
<input type="date" name="open_date">
<input type="text" name="genre">
<input type="text" name="watch_grade">
<input type="number" name="score">
<input type="text" name="poster_url">
<textarea name="description" id="" cols="30" rows="10"></textarea>
<input type="submit" value="submit">
</form>
{% endblock %}