part4-ML/from_1021_Django/django_movie_second/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('<username>/', views.profile, name="profile")
]

part4-ML/from_1021_Django/django_movie_second/movie_second/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

part4-ML/from_1021_Django/django_movie_second/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('<int:movie_pk>/', views.detail, name="detail"),
    path('<int:movie_pk>/edit/', views.edit, name="edit"),
    path('<int:movie_pk>/delete/', views.delete, name="delete"),
    path('<int:movie_pk>/ratings/new/', views.new_rating, name="new_rating"),
    path('<int:movie_pk>/ratings/<int:rating_pk>/delete/', views.delete_rating, name='delete_rating'),
]

part4-ML/from_1021_Django/django_movie_second/movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()
    poster = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.title

class Rating(models.Model):
    score = models.FloatField()
    content = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return str(self.score)

part4-ML/from_1021_Django/django_movie_second/movies/forms.py
from django import forms
from .models import Movie, Rating

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'description', 'poster',)

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('score', 'content',)

part4-ML/from_1021_Django/django_movie_second/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Rating
from .forms import MovieForm, RatingForm
from django.contrib.auth.decorators import login_required
from IPython import embed
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import numpy as np
from django.db.models import Avg

# Create your views here.
def index(request):
    # movies = Movie.objects.all()
    movies = Movie.objects.annotate(avg_score=Avg('rating__score')) # annotate : 주석을 단다! 
    # groupby연산을 한 놈을 model에 포함시켜 가져가기 => 기본적 쿼리는 다 가져감!
    # movie.avg_score
    context = {'movies':movies}
    return render(request, "movies/index.html", context)

def new(request):
    if request.method == "POST":
        form = MovieForm(request.POST, request.FILES) # 그냥 인자를 두개 때려넣어주면 됨!
        # form.poster = request.FILES.get("poster") # 이렇게는 안씀!
        # embed()
        print(form)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
        return redirect("movies:index")
    else:
        form = MovieForm()
        context = {'form' : form}
    return render(request, 'movies/new.html', context)

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    rating_form = RatingForm()
    ratings = Rating.objects.filter(movie=movie)
    scores = []
    for rating in ratings:
        scores.append(float(rating.score))
    # embed()
    mean_val = np.mean(scores)

    context = {
        'movie': movie,
        'rating_form':rating_form,
        'mean_val':mean_val,
        }

    return render(request, 'movies/detail.html', context)

def edit(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.user == movie.user:
        if request.method == "POST":
            form = MovieForm(request.POST, request.FILES, instance=movie)
            if form.is_valid():
                movie.title = form.cleaned_data.get("title")
                movie.description = form.cleaned_data.get("description")
                movie.poster = form.cleaned_data.get("poster")
                movie.save()
            return redirect("movies:index")
        else:
            form = MovieForm(instance=movie)
            context = {'form': form}
    return render(request, 'movies/new.html', context)

@require_POST
def delete(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        if request.user == movie.user:
            movie.poster.delete()
            movie.delete()
    return redirect("movies:index")
    
@require_POST
def new_rating(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        rating_form = RatingForm(request.POST)
        if rating_form.is_valid():
            rating = rating_form.save(commit=False)
            rating.movie = movie
            rating.user = request.user
            rating.save()
        return redirect("movies:detail", movie_pk)
    else:
        return HttpResponse("UNAUTHORIZED", status=401)

@require_POST
def delete_rating(request, movie_pk, rating_pk):
    if request.user.is_authenticated:
        rating = get_object_or_404(Rating, pk=rating_pk)
        if rating.user == request.user:
            rating.delete()
        return redirect("movies:detail", movie_pk)
    else:
        return redirect("accounts:login")

part4-ML/from_1021_Django/django_movie_second/movies/templates/movies/_movies.html
<!-- movies/_movies.html -->
<div class="card text-center mb-5">
    <div class="card-header">
        포스트 작성자 : {{ movie.user }}
    </div>
    <div class="card-body">
        <h5 class="card-title"> <a href="{% url 'movies:detail' movie.pk %}">
            {{ movie.title }}
        </a></h5>
        <p>평점 : {{ movie.avg_score|floatformat:2 }}</p>
        <img src="{{ movie.poster.url }}" alt="poster_img" width="200" height="300">
        <p class="card-text"></p>
    </div>
</div>

part4-ML/from_1021_Django/django_movie_second/movies/templates/movies/_nav.html
{% load gravatar %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'movies:index' %}">
        <img src="https://www.gravatar.com/avatar/{{user.email|makemd5}}?d=wavatar" alt="">
        Hello, {{ user.username }}!
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href=""></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:update' %}">정보 수정</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:change_password' %}">비밀번호 수정</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
            <li class="nav-item">
                <form action="{% url 'accounts:delete' %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="회원탈퇴" class="btn btn-danger">
                </form>
            </li>
        </ul>
    </div>

    {% else %}
    <a class="navbar-brand" href="{% url 'movies:index' %}">
        Hello, Guest!
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
        </ul>
    </div>
    {% endif %}

</nav>

part4-ML/from_1021_Django/django_movie_second/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>DETAIL</h1>
    <hr>
    <p>영화 번호 : {{ movie.pk }}</p>
    <p>영화 제목 : {{ movie.title }}</p>
    <img src="{{ movie.poster.url }}" width="200" height="300">
    <p>영화 설명 : {{ movie.description }}</p>
    <p>평균 평점 : {{ mean_val|floatformat:2 }}</p>
    <p>글 생성 시각 : {{ movie.created_at|date:"SHORT_DATE_FORMAT" }}</p>
    <p>글 수정 시각 : {{ movie.updated_at|date:"M, j, Y" }}</p>
    <p>작성자 : {{ movie.user }}</p>
    {% if request.user == movie.user %}
    <form action="{% url 'movies:edit' movie.pk %}">
        <input type="submit" value="EDIT">
    </form>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="DELETE">
    </form>
    {% endif %}
    <hr>
    {% if user.is_authenticated %}
        <form action="{% url 'movies:new_rating' movie.pk %}" method="POST">
            {% csrf_token %}
            {{ rating_form }}
            <input type="submit" value="NEW RATING">
        </form>
    {% else %}
        <a href="{% url 'accounts:login' %}">LOGIN FIRST, for RATING</a>
    {% endif %}
    <hr>
    <p>RATING LIST</p>
    {% for rating in movie.rating_set.all %}
        <div>
            <p> 점수 : {{ rating.score }}</p>
            <p> 한줄평 : {{ rating.content }}</p>
            <p>등록 시각 : {{ rating.created_at }}</p>
            {% if user == rating.user %}
                <form action="{% url 'movies:delete_rating' movie.pk rating.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="DELETE">
                </form>
            {% endif %}
        </div>
    <hr>
    {% endfor %}
    <form action="{% url 'movies:index' %}">
        <input type="submit" value="BACK">
    </form>
{% endblock %}

part4-ML/from_1021_Django/django_movie_second/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>MOVIES</h1>
    {% if user.is_authenticated %}
    <h2><a href="{% url 'movies:new' %}">[NEW]</a></h2>
    {% else %}
    <h2><a href="{% url 'accounts:login' %}">[글을 작성하시려면 로그인 해주세요]</a></h2>
    {% endif %}
    {% for movie in movies %}
        {% include 'movies/_movies.html' %}
        <hr>
    {% endfor %}
{% endblock %}

part4-ML/from_1021_Django/django_movie_second/movies/templates/movies/new.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    {% if request.resolver_match.url_name == 'new' %}
    <h1>NEW MOVIE</h1>
    {% else %}
    <h1>EDIT</h1>
    {% endif %}

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit="submit" reset="cancel" %}{% endbuttons %}
    </form>

{% endblock %}