part4-ML/from_1021_Django/django_form/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('<username>/', views.profile, name="profile"),
]

part4-ML/from_1021_Django/django_form/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/comments/', views.comments_create, name="comments_create"),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name="comments_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name="follow"),
    path('<int:hash_pk>/hashtag/', views.hashtag, name="hashtag"),
]

part4-ML/from_1021_Django/django_form/form/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

part4-ML/from_1021_Django/django_form/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followees")

part4-ML/from_1021_Django/django_form/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 이렇게 해주면 user에 대한 foreign key가 생긴 것! # AUTH_USER_MODEL : string return?
    hashtags = models.ManyToManyField(Hashtag, blank=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="like_articles",
        blank=True,
    )

    class Meta:
        ordering = ('-pk', )

    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ('-pk', )

part4-ML/from_1021_Django/django_form/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model() # 현재 활성화된 모델 가져와줌
        fields = ('first_name', 'last_name', 'email',)

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # username, password1, password2, email
        model = get_user_model() # 원래는 auth.User 였을 텐데 accounts.User 참조
        fields = UserCreationForm.Meta.fields + ('email', )

part4-ML/from_1021_Django/django_form/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.
def signup(request):

    if request.user.is_authenticated:
        return redirect("articles:index")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # signup 후 바로 login되게 하기
            auth_login(request, user)
            return redirect("articles:index")
    else:
        form = CustomUserCreationForm()
    context = {'form' : form}
    return render(request, 'accounts/auth_form.html', context)

def login(request):

    if request.user.is_authenticated:
        return redirect("articles:index")

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or "articles:index")
    else:
        form = AuthenticationForm()
    context = {'form' : form}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect("articles:index")

@require_POST
def delete(request):
    request.user.delete()
    return redirect("articles:index")

def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("articles:index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'accounts/auth_form.html', context)

@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save() # 이걸 해줘야 db에 반영!
            update_session_auth_hash(request, form.user) 
            # 현재 사용자의 인증 세션이 무효화되는 것을 막고,
            # 세션을 유지한 상태로 비밀번호를 업데이트 시켜준다.
            return redirect("articles:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {'form':form}
    return render(request, 'accounts/auth_form.html', context)

def profile(request, username):
    # User model을 가져올 수 있는 2가지 방법
    # 1. get_user_model() - object return (models.py 제외 전부)
    # 2. settings.AUTH_USER_MODEL - string return (models.py)
    person = get_object_or_404(get_user_model(), username=username)
    context = {'person':person}
    return render(request, 'accounts/profile.html', context)

part4-ML/from_1021_Django/django_form/accounts/templates/accounts/auth_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
<h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
<h1>로그인</h1>
{% elif request.resolver_match.url_name == 'update' %}
<h1>회원정보 수정</h1>
{% else %}
<h1>비밀번호 변경</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="submit" reset="cancel" %}{% endbuttons %}
</form>

{% endblock %}

part4-ML/from_1021_Django/django_form/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>비밀번호 변경</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="비밀번호 변경" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock %}

part4-ML/from_1021_Django/django_form/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block body %}
<h1>로그인</h1>
<form action="" method="POST">
    {% csrf_token %}
    <!-- 이전엔 미리 만들어진 로그인 폼 객체를 날림! -->
    {% bootstrap_form form %}
    {% buttons submit="로그인" reset="Cancel" %}{% endbuttons %}
</form>
<a href="{% provider_login_url 'kakao' %}" class="btn btn-warning">카카오 로그인</a>
{% endblock %}

part4-ML/from_1021_Django/django_form/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ person.username }}'s Profile</h1>
<hr>
<h3>{{ person.username }}이 작성한 글</h3>

<div class="row">
    <!-- 이렇게 안써주면 article을 한번 부를때마다 쿼리 날림 -->
    {% with articles=person.article_set.all %}
    {% for article in articles %}
        <div class="col-4 my-2">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                <h5 class="card-title">{{ article.content|truncatechars:20 }}</h5>
                <p class="card-text">{{ article.like_users.count }}명이 좋아하는 글</p>
                <p class="card-text">{{ article.commnet_set.count }}개의 댓글</p>
                <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">[DETAIL]</a>
                </div>
            </div>
        </div>
    {% endfor %}
    {% endwith %}
</div>

<hr>

<h3>{{ person.username }}이 작성한 댓글</h3>
<div class="row">
    {% with comments=person.comment_set.all %}
    {% for comment in comments %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <blockquote class="blockquote">
                    <p>{{ comment.content }}</p>
                    <footer class="blockquote-footer">
                        {{comment.created_at|date:"SHORT_DATE_FORMAT"}}
                    </footer>
                </blockquote>
            </div>
        </div>
    {% endfor %}
    {% endwith %}
</div>

{% endblock %}

part4-ML/from_1021_Django/django_form/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>회원가입</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="회원가입" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock %}

part4-ML/from_1021_Django/django_form/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>회원 정보 수정</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="회원 정보 수정" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock %}